name: AWS WebSocket Serverless Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_DEFAULT_REGION: eu-west-2

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Deploy
        with:
          CONFIGURATION: Release
          S3BUCKET: aws-lambda-test-1
          VCSREF: ${{ github.sha }}
          VCSBRANCH: ${{ github.ref }}
        run: ./build.sh --target=Deploy
